// <auto-generated />
namespace BridgeLesson.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bridgeConventionToSystemRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bridgeConventionToSystemRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201605050913051_bridgeConventionToSystemRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
